# Generated by Django 3.2.9 on 2022-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
    ]
